title: Trevor Maxwell
logo: /assets/images/profile_cropped.jpg
# show_downloads: true
theme: jekyll-theme-minimal

description:
  <p align="center">
  <a href="assets/documents/Resume_General.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/trevormaxwell/">LinkedIn</a> |
  <a href="https://github.com/trevormaxwell/">GitHub</a>
  </p>  
